repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/dnephin/pre-commit-golang
  sha: v0.3.3
  hooks:
  - id: go-unit-tests
  - id: golangci-lint
- repo: https://github.com/Lucas-C/pre-commit-hooks-go
  sha: v1.0.0
  hooks:
  - id: checkmake
- repo: https://github.com/mailchain/pre-commit
  sha: v0.0.4
  hooks:
  - id: generate-api-docs
  - id: add-license
